// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWJawN1HgHEmRiSHdgF7vJCdcsvhozfqk',
    appId: '1:725290983896:web:bfdb69b74062d1530cd2ad',
    messagingSenderId: '725290983896',
    projectId: 'chat-app-b2c38',
    authDomain: 'chat-app-b2c38.firebaseapp.com',
    storageBucket: 'chat-app-b2c38.appspot.com',
    measurementId: 'G-N6QPS2TPET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwzQiXnL2UWxJsq_GehkQbIOxqBLzmAII',
    appId: '1:725290983896:android:b1a313d567a8d8170cd2ad',
    messagingSenderId: '725290983896',
    projectId: 'chat-app-b2c38',
    storageBucket: 'chat-app-b2c38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDaUYgykLt-hSjo7AzV4nsShHLVmHjCEQ',
    appId: '1:725290983896:ios:1072de8e50a452b40cd2ad',
    messagingSenderId: '725290983896',
    projectId: 'chat-app-b2c38',
    storageBucket: 'chat-app-b2c38.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDaUYgykLt-hSjo7AzV4nsShHLVmHjCEQ',
    appId: '1:725290983896:ios:e4bec3e99fbe1c9c0cd2ad',
    messagingSenderId: '725290983896',
    projectId: 'chat-app-b2c38',
    storageBucket: 'chat-app-b2c38.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
